### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by ChristopherA** [dcdpr/jsonld-cpp#1]
Is there any roadmap on next steps for this project, in particular, conformance to VC test suite and JSON-LD 1.1 signing?

I'd like to start signing with our new command-line tools soon, and in the FullyNoded 2 wallet.

-- Christopher Allen

/cc @wolfmcnally @fonta1n3

**Comment by danpape** [comment]
As of the last commit, several months ago, jsonld-cpp currently supports "expand()", "toRdf()" and "normalize()" JSON-LD operations, and passes the v1.0 JSON-LD api test suite cases for those operations. This should be sufficient for us to add signing and verification of VC documents to our BTCR code. However, we wanted to be v1.1 conformant and we are actively working on jsonld-cpp again. Our roadmap looks like: a) outputting test results in the official format needed to submit an implementation report for https://json-ld.org/; b) filling in some gaps with our v1.1-supporting code so we can pass all the v1.1 tests in JSON-LD api test suite; c) do any work needed for the VC test suite; d) integrate jsonld-cpp with BTCR.

I just looked through all the VC test suite cases, and they all look like JSON-LD v1.0 documents, so we could perhaps work on step c before step b. It will probably take a few to several weeks for us to get all of this completed. We will keep you up to date.

**Comment by dcdpr** [comment]
We're very close to a v1.1 compliant release that supports "expand()", "toRdf()" and "normalize()".

**Comment by qikdauie** [comment]
Hello everyone. Has development on this project been discontinued in favor of something else?

**Comment by rxgrant** [comment]
We have a big pull request with ongoing progress. https://github.com/dcdpr/jsonld-cpp/pull/2

**Comment by dcdpr** [comment]
Our compliance with the specification can be seen  
[here](https://w3c.github.io/json-ld-api/reports/#subj_jsonld_cpp_C_).
